In [13]:
#numpy task
import numpy as np

In [ ]:
#create numpy multidimentional array
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# accessing element
print("first Value =", arr[0,0])
print("second Row Third Value =", arr[1,2])
print("third Row Second Value =", arr[2,1])

first Value = 10
second Row Third Value = 60
third Row Second Value = 80


In [ ]:
#addition
print(arr + 10)

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]


In [ ]:
#substraction
print(arr - 5)

[[ 5 15 25]
 [35 45 55]
 [65 75 85]]


In [ ]:
#multiplication
print(arr * 2)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


In [ ]:
#division
print(arr / 10)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#mumpy methods

# 1. shape
print("1. Shape:", arr.shape)

# 2. size
print("2. Size:", arr.size)

# 3. ndim
print("3. Dimension:", arr.ndim)

# 4. dtype
print("4. Data Type:", arr.dtype)

# 5. max()
print("5. Maximum:", np.max(arr))

# 6. min()
print("6. Minimum:", np.min(arr))

# 7. sum()
print("7. Sum:", np.sum(arr))

# 8. mean()
print("8. Mean:", np.mean(arr))

# 9. reshape()
print("9. Reshape:\n", arr.reshape(1, 9))

# 10. flatten()
print("10. Flatten:", arr.flatten())

# 11. transpose()
print("11. Transpose:\n", arr.T)

# 12. sort()
print("12. Sort:\n", np.sort(arr))

# 13. sqrt()
print("13. Square Root:\n", np.sqrt(arr))

# 14. power()
print("14. Power:\n", np.power(arr, 2))

# 15. copy()
arr_copy = arr.copy()
print("15. Copy:\n", arr_copy)


1. Shape: (3, 3)
2. Size: 9
3. Dimension: 2
4. Data Type: int64
5. Maximum: 90
6. Minimum: 10
7. Sum: 450
8. Mean: 50.0
9. Reshape:
 [[10 20 30 40 50 60 70 80 90]]
10. Flatten: [10 20 30 40 50 60 70 80 90]
11. Transpose:
 [[10 40 70]
 [20 50 80]
 [30 60 90]]
12. Sort:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
13. Square Root:
 [[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]
 [8.36660027 8.94427191 9.48683298]]
14. Power:
 [[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]
15. Copy:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
